version: "{build}"

clone_folder: c:\gopath\src\github.com\Oppodelldog\droxy

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1
  GOVERSION: 1.11

init:
  - git config --global core.autocrlf input

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - choco install bzr
  - set Path=c:\go\bin;c:\gopath\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\%Path%
  - go version
  - go env
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go get ./...
  - go build

build: false
deploy: false

test_script:
  - go build github.com/Oppodelldog/droxy
  - for /f "" %%G in ('go list github.com/Oppodelldog/droxy/...') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)